apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: myhttpd
  namespace: {{ .Release.Namespace }}
spec:
  path: /root/myapp/v1
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: myhttpd
