apiVersion: v1
kind: Service
metadata:
  name: myhttpd
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myhttpd
