apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhttpd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myhttpd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myhttpd
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: myapache
        ports:
        - containerPort: 8080
          name: metrics-port
          protocol: TCP
        env:
          - name: MYNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      serviceAccount: default
